version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_network

volumes:
  db_data:

networks:
  db_network:
